### ISSUE TITLE
咨询您关于键盘和固件制作的博客教程。

### ISSUE THREAD

**Issue by jiaxin96** [chie4hao/qmk_firmware_nrf52840#1]
大佬好，我对您的这个工作非常感兴趣，可惜没能早看到这个项目，我多方打听后得知您的博客已经关闭，我恳请您能在开源平台重新发布一下您的相关的蓝牙键盘的文章。
过期博文地址：http://chie4.com/bluetooth_keyboard_build_log/

**Comment by joric** [comment]
Borrowed eeprom.c from here (sekigon's eeprom.c wasn't functional). Cool stuff! I have a tutorial (kind of): https://github.com/joric/nrfmicro/wiki/Software
